### ISSUE TITLE
Updating to current latest (v0.6.5)

### ISSUE THREAD

**Issue by SunP04** [allxrise/devbuckets#2]
I've already done a [past PR](https://github.com/allxrise/devbuckets/pull/1) on the topic, but I closed it since it's not really my thing and it was unfinished.

It would be nice to have the compiler to be at the latest version [v0.6.5](https://github.com/c3lang/c3c/releases/tag/v0.6.5), instead of the current one in this bucket (aka v.0.6.4)

Thanks in advance, Sun.

**Comment by allxrise** [comment]
This scoop repo was just a testing so I thought nobody will see it... I abandoned it because I wasn't able to implement autoupdate, c3 repo lacks sharing SHA sums of the release. But anyway, I will update it to the latest and put the proper hash to manifest ASAP.

**Comment by allxrise** [comment]
I updated to [v0.6.5](https://github.com/c3lang/c3c/releases/tag/v0.6.5) but I'm currently on Linux so I can't really check if it works or not. I won't close this issue until you approve it works.

**Comment by SunP04** [comment]
It updated sucessfully, you can check it by searching in [their site](https://scoop.sh) or by seeing the image below.

![image](https://github.com/user-attachments/assets/6f5fd81e-d450-4703-86c4-e847a103e718)

Thanks!

**Comment by allxrise** [comment]
Thank you for showing this to me, I thought I have to make a pull request for main scoop repo to show it at least on their site. Closing this issue now.
